insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'admin', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'ADMIN');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'user', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');

-- Mock users
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ggossage0@sohu.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'fczyz1@japanpost.jp', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'tashdown2@google.com.br', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'hbarrus3@apple.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ewarbey4@oaic.gov.au', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'sgoroni5@amazon.co.jp', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'flowen6@tuttocitta.it', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'edashper7@seattletimes.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'btraher8@reference.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'qsavaage9@rediff.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'iingledewa@ehow.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'lbanbridgeb@github.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'arainsc@miibeian.gov.cn', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'rdegouyd@economist.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'avonwelldune@gov.uk', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'myakubovf@unc.edu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'lpudding@bbb.org', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'tmundowh@theglobeandmail.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'abarochi@bloglines.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'bmasij@msn.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'bgrundellk@creativecommons.org', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'disaql@ca.gov', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ssautterm@prweb.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'rdooren@europa.eu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'btunsleyo@ibm.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'dstanleyp@berkeley.edu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'gwinkworthq@360.cn', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'fradnager@pcworld.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'mdionisiis@mayoclinic.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'snowakowskit@tinypic.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'abrymhamu@abc.net.au', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'hlathyv@microsoft.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'kgomeryw@is.gd', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'rhamorx@reverbnation.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'nmatkovicy@nature.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'gzanettoz@ibm.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'hhasnney10@cnbc.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'agreenland11@hud.gov', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'grandle12@ucsd.edu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'edeinert13@ucoz.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'bclatworthy14@wunderground.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'wstevens15@harvard.edu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'landerton16@addthis.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'jrattrie17@mozilla.org', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'jrandal18@ucoz.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'vcota19@blog.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'gvarndall1a@census.gov', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'thorick1b@techcrunch.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'tdaingerfield1c@miitbeian.gov.cn', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'tdedham1d@blogtalkradio.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'afranseco1e@odnoklassniki.ru', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'bbaron1f@chronoengine.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ddoge1g@thetimes.co.uk', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'briddett1h@php.net', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'aostler1i@booking.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'rbolden1j@tinyurl.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ggrivori1k@etsy.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'lcapron1l@ovh.net', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'mparriss1m@youtu.be', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'cmcgavin1n@flavors.me', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ghembling1o@earthlink.net', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'cruddle1p@phpbb.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'yjose1q@ft.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'iheiton1r@ask.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'shelkin1s@cornell.edu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'phuntingford1t@storify.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'pciani1u@cloudflare.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'skeeffe1v@miitbeian.gov.cn', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'chartman1w@flickr.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'hbucknill1x@stanford.edu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ecescon1y@epa.gov', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ccarayol1z@hostgator.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'coconnor20@nasa.gov', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'hmccaskill21@google.com.hk', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ksugars22@nps.gov', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ntuckwell23@fc2.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ebunton24@phoca.cz', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'zdoohey25@shutterfly.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ahacksby26@webeden.co.uk', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'mhallad27@parallels.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'gwhyborn28@typepad.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'cflement29@epa.gov', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ebibb2a@angelfire.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'crittmeier2b@umn.edu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'rvanderbrugge2c@archive.org', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'jskeates2d@prweb.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'oguilbert2e@wix.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'pbaptiste2f@feedburner.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'lkornilov2g@linkedin.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'hmcvicker2h@cdc.gov', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'ibrisker2i@istockphoto.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'cspary2j@jimdo.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'wspiers2k@storify.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'bgerrett2l@ox.ac.uk', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'bjouhning2m@uiuc.edu', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'cpizey2n@photobucket.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'tmeasey2o@mediafire.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'sohartigan2p@yellowbook.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'yorbell2q@behance.net', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');
insert into USER (ID, EMAIL, PASSWORD, ROLE) values (nextval('USER_SEQ'), 'jisakov2r@bloglines.com', '$2a$10$dZsdQUfAfZVCz7cUhl2uMutgekw8uOYKl6sb54JBKwwyYH/zvNVmC', 'USER');

-- Mock profiles
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION) values (nextval('PROFILE_SEQ'), 1, 'John', 'Doe', true, false);
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 2, 'Dacie', 'Roper', '2021-08-03', 'Colorado Springs', 'Colorado', '7193966463', true, true, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 3, 'Hersh', 'Abbets', '2022-02-19', 'Savannah', 'Georgia', '9121117780', true, true, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 4, 'Twila', 'Crocetti', '2021-06-09', 'Melbourne', 'Florida', '3219781365', true, true, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 5, 'Flor', 'Brydon', '2022-05-15', 'New York City', 'New York', '2125914736', false, false, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 6, 'Julius', 'Newgrosh', '2021-11-30', 'Sacramento', 'California', '9166431429', false, true, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 7, 'Janela', 'Baitey', '2022-02-15', 'Newark', 'New Jersey', '9739725627', false, true, 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 8, 'Florence', 'Blaase', '2022-02-07', 'San Francisco', 'California', '4153145374', false, false, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 9, 'Frasco', 'Plevin', '2021-12-10', 'Columbus', 'Ohio', '6147997619', false, true, 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 10, 'Caz', 'Groneway', '2021-08-25', 'Winston Salem', 'North Carolina', '7044356419', false, true, 'Phasellus in felis. Donec semper sapien a libero.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 11, 'Rockey', 'Howsan', '2021-12-04', 'Phoenix', 'Arizona', '4806527874', true, true, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 12, 'Jerrold', 'Dallyn', '2021-12-28', 'Suffolk', 'Virginia', '7576802878', true, false, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 13, 'Ofilia', 'Rude', '2021-11-01', 'Fresno', 'California', '5596251908', false, false, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 14, 'Archer', 'Weinmann', '2021-10-12', 'Louisville', 'Kentucky', '5025337456', false, false, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 15, 'Bill', 'Goodram', '2022-03-03', 'Sandy', 'Utah', '8019252868', true, true, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 16, 'Glenden', 'Owers', '2022-01-25', 'Richmond', 'California', '5104517649', true, false, 'Pellentesque ultrices mattis odio.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 17, 'Monah', 'Chess', '2022-05-10', 'New York City', 'New York', '2125315211', true, false, 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 18, 'Evangelia', 'Malling', '2021-12-14', 'Frederick', 'Maryland', '2409096316', true, true, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 19, 'Orin', 'Kendrew', '2022-04-26', 'Houston', 'Texas', '7133052747', true, false, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 20, 'Minetta', 'Newdick', '2021-08-17', 'Lansing', 'Michigan', '5171389895', true, true, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 21, 'Banky', 'Baser', '2022-04-01', 'Gatesville', 'Texas', '2541446054', false, true, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 22, 'Suzanne', 'Rudledge', '2021-12-06', 'Houston', 'Texas', '2815271633', false, false, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 23, 'Mireille', 'Gerardi', '2021-10-30', 'Saint Petersburg', 'Florida', '7272353426', false, false, 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 24, 'Thurstan', 'Wildash', '2022-02-19', 'Dayton', 'Ohio', '9376165142', false, false, 'Ut tellus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 25, 'Dianemarie', 'Gopsill', '2021-10-18', 'Albany', 'New York', '5185969737', false, false, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 26, 'Erhart', 'Hastings', '2022-01-09', 'Arlington', 'Virginia', '5716136327', false, false, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 27, 'Celestine', 'Brettelle', '2021-06-26', 'Naples', 'Florida', '3059090913', true, true, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 28, 'Hugh', 'Greenard', '2021-05-27', 'Shawnee Mission', 'Kansas', '9134590203', true, false, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 29, 'Gwenni', 'Staveley', '2021-06-29', 'El Paso', 'Texas', '9156564922', false, true, 'Etiam faucibus cursus urna. Ut tellus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 30, 'Hugibert', 'Kenworthey', '2022-02-13', 'Albany', 'New York', '5187796624', false, true, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 31, 'Chelsea', 'Solleme', '2021-05-22', 'Oklahoma City', 'Oklahoma', '4056687962', true, false, 'Quisque porta volutpat erat.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 32, 'Faydra', 'Pilmer', '2021-10-17', 'Jamaica', 'New York', '2129870982', false, false, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 33, 'Tony', 'Dulton', '2022-02-12', 'Lincoln', 'Nebraska', '4028947983', false, true, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 34, 'Ashleigh', 'Monkeman', '2022-04-13', 'Lake Charles', 'Louisiana', '3375953414', true, true, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 35, 'Ogden', 'Woodthorpe', '2022-05-02', 'Fort Wayne', 'Indiana', '2603663989', true, true, 'Phasellus sit amet erat. Nulla tempus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 36, 'Norri', 'Timblett', '2021-11-29', 'Olympia', 'Washington', '3607105227', true, true, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 37, 'Miles', 'Dorracott', '2021-07-25', 'Wilmington', 'Delaware', '3026766875', true, true, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 38, 'Emmye', 'Yurchishin', '2022-02-10', 'Salt Lake City', 'Utah', '8016784490', true, false, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 39, 'Melosa', 'Hardin', '2021-10-17', 'Akron', 'Ohio', '3307326882', false, true, 'Etiam pretium iaculis justo.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 40, 'Yevette', 'Youhill', '2021-11-13', 'Memphis', 'Tennessee', '9011626198', true, false, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 41, 'Gunther', 'Norsworthy', '2021-06-18', 'Austin', 'Texas', '5128574093', true, false, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 42, 'Conny', 'Harmar', '2021-07-22', 'Killeen', 'Texas', '2548832887', true, true, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 43, 'Amity', 'Skaife d''Ingerthorpe', '2021-06-07', 'Baltimore', 'Maryland', '4107268959', true, true, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 44, 'Jere', 'Jutson', '2022-03-29', 'Seattle', 'Washington', '2066799147', false, true, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 45, 'Rickard', 'Scarisbrick', '2022-03-28', 'San Francisco', 'California', '4158619025', false, true, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 46, 'Bernelle', 'Lill', '2021-11-06', 'Sioux Falls', 'South Dakota', '6053581418', false, false, 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 47, 'Marley', 'Donaghie', '2022-02-02', 'Oklahoma City', 'Oklahoma', '4058282262', false, true, 'In congue.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 48, 'Domeniga', 'Boyes', '2021-07-08', 'Annapolis', 'Maryland', '3011654542', false, true, 'Nulla facilisi.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 49, 'Amity', 'Beamiss', '2021-11-13', 'Colorado Springs', 'Colorado', '7198688979', false, false, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 50, 'Joli', 'Troubridge', '2022-03-21', 'Atlanta', 'Georgia', '6781613486', false, true, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 51, 'Lindy', 'Lean', '2022-01-31', 'Erie', 'Pennsylvania', '8144017306', true, false, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 52, 'Elinore', 'Slany', '2021-09-21', 'Pompano Beach', 'Florida', '7545971996', true, false, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 53, 'Chantalle', 'Boggers', '2021-11-01', 'Springfield', 'Illinois', '2175900589', false, false, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 54, 'Rhys', 'Heape', '2022-02-10', 'Pittsburgh', 'Pennsylvania', '4125773809', false, true, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 55, 'Chelsy', 'Whisby', '2021-09-08', 'Dallas', 'Texas', '4696826830', true, false, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 56, 'Ryann', 'Novis', '2021-10-02', 'Sioux Falls', 'South Dakota', '6058927126', true, false, 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 57, 'Javier', 'Gallemore', '2022-02-18', 'Orlando', 'Florida', '4079635504', true, true, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 58, 'See', 'Lisciandro', '2021-10-20', 'Washington', 'District of Columbia', '2021147576', false, false, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 59, 'Skelly', 'Peakman', '2021-12-09', 'Indianapolis', 'Indiana', '7652838995', true, false, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 60, 'Carmelita', 'Gherardesci', '2022-01-17', 'Lancaster', 'California', '6611939653', false, true, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 61, 'Brandais', 'De Giorgis', '2021-11-09', 'Tacoma', 'Washington', '2539847619', true, false, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 62, 'Margit', 'Wehden', '2021-11-08', 'Syracuse', 'New York', '3155711894', false, false, 'In blandit ultrices enim.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 63, 'Bridget', 'Lujan', '2021-07-23', 'El Paso', 'Texas', '9153435040', true, false, 'Donec vitae nisi.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 64, 'Regine', 'Dutnall', '2022-01-01', 'Springfield', 'Illinois', '2178381737', false, false, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 65, 'Dion', 'Kunath', '2021-10-03', 'Ridgely', 'Maryland', '4109836234', false, false, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 66, 'Myra', 'Cummine', '2021-09-23', 'Lansing', 'Michigan', '5177040896', false, false, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 67, 'Carmine', 'Tripcony', '2022-01-14', 'Rochester', 'New York', '5856198030', true, true, 'Etiam justo. Etiam pretium iaculis justo.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 68, 'Duncan', 'Stearn', '2021-10-19', 'Kansas City', 'Kansas', '8161988232', false, false, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 69, 'Ferris', 'MacKaig', '2022-03-14', 'Des Moines', 'Iowa', '5155663461', true, false, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 70, 'Sharron', 'Lasslett', '2021-08-29', 'Greensboro', 'North Carolina', '3361245116', false, true, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 71, 'Edsel', 'Francke', '2021-06-15', 'Lubbock', 'Texas', '8068224555', true, false, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 72, 'Terry', 'Camilletti', '2021-12-05', 'Chicago', 'Illinois', '7734327425', true, false, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 73, 'Kenon', 'Fairbrother', '2022-04-13', 'Springfield', 'Massachusetts', '4137471368', true, false, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 74, 'Sibby', 'Butland', '2022-04-26', 'Pittsburgh', 'Pennsylvania', '4127199554', true, true, 'Vivamus tortor. Duis mattis egestas metus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 75, 'Antons', 'Chisolm', '2021-11-25', 'Saint Louis', 'Missouri', '3147818491', false, false, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 76, 'Susanne', 'Corless', '2021-11-07', 'Minneapolis', 'Minnesota', '6128357785', true, true, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 77, 'Jenny', 'Vinall', '2022-04-02', 'Amarillo', 'Texas', '8068249135', false, false, 'Nunc purus. Phasellus in felis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 78, 'Estell', 'Mannock', '2021-06-02', 'Springfield', 'Ohio', '9372934648', false, true, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 79, 'Rollie', 'Descroix', '2021-09-15', 'Los Angeles', 'California', '2132406389', false, false, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 80, 'Rosemonde', 'Stockau', '2021-07-02', 'Houston', 'Texas', '7132963089', true, false, 'Sed accumsan felis.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 81, 'Link', 'Norgan', '2021-08-23', 'Louisville', 'Kentucky', '5025993206', true, false, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 82, 'Cheston', 'Ashman', '2021-07-09', 'Olympia', 'Washington', '3606533564', false, true, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 83, 'Bradney', 'Eastbrook', '2021-08-05', 'Lancaster', 'California', '6614917785', true, false, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 84, 'Chase', 'Juschke', '2022-05-03', 'El Paso', 'Texas', '9159700899', true, false, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 85, 'Matthus', 'Paolini', '2022-03-19', 'Kansas City', 'Missouri', '8166230642', false, false, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 86, 'Harris', 'O''Breen', '2022-01-08', 'Albany', 'New York', '5181493692', true, true, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 87, 'Bria', 'Ramstead', '2022-04-14', 'San Diego', 'California', '6191945656', false, false, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 88, 'Frasco', 'Duddy', '2021-12-28', 'Jackson', 'Mississippi', '6012609281', false, true, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 89, 'Aubrey', 'Dripps', '2022-04-15', 'Houston', 'Texas', '7136524599', true, true, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 90, 'Sonny', 'Drynan', '2022-01-15', 'Lexington', 'Kentucky', '8593794389', true, true, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 91, 'Allina', 'Borer', '2022-03-09', 'Brea', 'California', '7141538781', true, false, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 92, 'Ceciley', 'Evetts', '2022-04-27', 'Las Vegas', 'Nevada', '7024003520', false, true, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 93, 'Bili', 'Goozee', '2022-02-22', 'Santa Ana', 'California', '6195569209', false, false, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 94, 'Shepperd', 'Pond', '2021-10-04', 'Nashville', 'Tennessee', '6158576662', false, false, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 95, 'Ronica', 'Tadgell', '2021-11-11', 'Paterson', 'New Jersey', '8622286635', true, true, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 96, 'Edgar', 'Rofe', '2022-04-03', 'Sacramento', 'California', '9165790165', false, false, 'Praesent blandit. Nam nulla.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 97, 'Dwain', 'McCartney', '2022-03-02', 'Kansas City', 'Missouri', '8166098274', false, true, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 98, 'Darda', 'Berriman', '2021-09-19', 'Savannah', 'Georgia', '9121488044', false, false, 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 99, 'Shalna', 'Neilus', '2022-05-12', 'Boise', 'Idaho', '2084300170', true, true, 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 100, 'Arline', 'Blatcher', '2022-02-06', 'Baton Rouge', 'Louisiana', '2255183098', false, true, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into PROFILE (ID, USER_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, CITY, PROVINCE, PHONE_NUMBER, IS_NEW, HAS_DISMISSED_COMPLETE_PROFILE_NOTIFICATION, EXPERIENCE) values (nextval('PROFILE_SEQ'), 101, 'Lynnell', 'Deroche', '2022-01-24', 'Knoxville', 'Tennessee', '8655661144', false, false, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');

insert into EMPLOYEE (ID, USERNAME) values (1, 'Yanis');
insert into EMPLOYEE (ID, USERNAME) values (2, 'Sharon');
insert into EMPLOYEE (ID, USERNAME) values (3, 'Femke');
insert into EMPLOYEE (ID, USERNAME) values (4, 'Anna');

insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'cursus','2022-05-10 8:00:00', '2022-05-10 12:00:00', 'cursus dans', 1);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'webinar','2022-06-10 9:00:00', '2022-06-10 13:00:00', 'webinar limits academy', 2);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'webinar','2022-08-11 8:00:00', '2022-08-11 12:00:00', 'webinar limits academy', 3);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'meeting dans','2022-05-19 16:00:00', '2022-05-19 18:00:00', 'meeting met Anna voor Dans workshop', 4);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'meeting zang','2022-05-19 9:00:00', '2022-05-19 14:00:00', 'meeting met Yanis voor Dans workshop', 3);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'staking','2022-05-24 8:00:00', '2022-05-24 12:00:00', 'algemene staking', 4);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'lunch','2022-05-28 9:00:00', '2022-05-28 13:00:00', 'lunch met Anna', 3);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'paper','2022-05-28 8:00:00', '2022-05-28 12:00:00', 'paper', 4);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'schooltaak','2022-05-28 7:00:00', '2022-05-28 11:00:00', 'taak design', 3);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'meeting','2022-05-20 8:00:00', '2022-05-20 12:00:00', 'Meeting met Femke', 3);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'meeting','2022-05-28 12:00:00', '2022-05-28 16:00:00', 'Meeting met Sharon', 3);
insert into event(id, title, start, finish, description, EMPLOYEE_ID)
values ((nextval('EVENT_SEQ')), 'meeting','2022-05-28 16:00:00', '2022-05-28 18:00:00', 'Meeting met Yanis', 3);



INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Dans', 'Deze dansles is speciaal voor mensen met een verstandelijke beperking. Ze leren verschillende dansen, losse dansen met eenvoudige bewegingen, party dance, maar ook stijldansen zoals Quickstep, Engelse wals, ChaChaCha en Tango. \nBij deze groep is het vooral belangrijk dat ze zich even lekker kunnen bewegen en uiten en dat ze andere mensen ontmoeten. Ervaring leert dat ze het als heel erg leuk ervaren en dit met heel veel plezier doen.
\nNatuurlijk is het niet zomaar iets doen, maar zit er ook een doel achter. Ze zijn namelijk bezig met bewegen op muziek en dat is goed voor de motorische ontwikkeling, sociale ontwikkeling en lichamelijke ontwikkeling. Het plezier dat wordt beleefd door te leren dansen is uiteraard weer goed voor hun zelfvertrouwen.
De dansen zijn zo gemaakt dat iedere cursist op zijn eigen manier kan meedoen. Er wordt rekening gehouden met de beperkingen van de cursisten en ze worden gestimuleerd steeds een beetje meer te kunnen. Ze worden bij ons niet geconfronteerd met hun niet kunnen maar juist met wat ze WEL kunnen. Dit stimuleert ze en geeft ze zelfvertrouwen!',
        'Ze leren verschillende dansen, losse dansen met eenvoudige bewegingen, party dance, maar ook stijldansen zoals Quickstep, Engelse wals, ChaChaCha en Tango. ',
        'Mechelen', 'dans',false);
INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Zang',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Je hebt geen muzikale voorkennis nodig. Wees dus niet bang om de stap te zetten naar vocal coaching.
Zangles is ook vooral kei hard genieten van jouw moment!', 'Antwerpen', 'zang',false);
INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Acteren',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Doorheen de opleiding wordt er
gewerkt met verschillende stijlen
en theatervormen: komedie,
tragedie, beweging, maskerspel, figurentheater en nog veel meer', 'Mechelen', 'theater',false);
INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Dans: LMTS KIDS',
        'Deze dansgroep bestaat uit onze jongste leden die elke week weer op hun favoriete liedjes begeleid worden door Anna. Zij neemt hen mee naar hun grootste idolen door op hun muziek wekelijks een dans aan te leren op een speelse manier.',
        'Deze dansgroep bestaat uit onze jongste leden die niet graag stil zitten met hun dansbenen!', 'Antwerpen', 'dans',true);

INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Dans: LMTS JUNIORS',
        'In deze workshop krijgen de LIMITS-artiesten les van professionele dansleerkrachten Anna en Yanis. Ze krijgen de basis aangeleerd van verschillende stijlen zoals HipHop, Modern, Ragga en Jazz. Samen met de docenten werken ze elke paar maand naar een spetterende choreografie. ',
        'Krijg dansles van onze professionele dansleerkrachten en leer verschillende dansstijlen.','Mechelen', 'dans',true);
INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Dans: LMTS ELITE',
        'In de laatste dansgroep zitten de meest gevorderde dansers van LMTS ACADEMY. Zij worden voorzien van een iets moeilijker niveau om de extra uitdaging aan te gaan. Yanis leert ze de meer uitdagende passen aan binnen alle stijlen die ze aanbieden.',
        'Een dansgroep voor onze gevorderde LMTS-artiesten die niet bang zijn voor een uitdaging.', 'Mechelen', 'dans',true);
INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Theater',
        'In de workshop theater leiden we de LMTS-artiesten op tot de fijnste acteurs/actrices. Samen met professionele acteurs zoals Walter Bale en Kurt Rogiers werken ze elke paar maand toe naar een bekend toneelstuk zoals ‘Romeo & Julia’, ‘Otello’… ',
        'Heb je altijd al willen schitteren op het podium of voor een camera? Dan is deze workshop iets voor jou!', 'Mechelen', 'theater',true);
INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Zang',
        'De zangworkshops worden gegeven door Yanis. Hij zal zich ontfermen over zowel de kleinsten als oudste zangroepen. Ze werken elke paar maand toe naar een cover van een bekend lied uit de muziekwereld. Zo coveren ze liedjes zoals ‘Laat de zon in je hart’, ‘Uptown girl’…',
        'Voor jong en oud, iedereen die zijn innerlijke nachtegaal naar boven wilt brengen samen met onze begeleiding!', 'Mechelen', 'zang',true);
INSERT INTO COURSE (ID, NAME, DESCRIPTION, SHORTDESCRIPTION, LOCATION, category,workshop)
VALUES (nextval('COURSE_SEQ'), 'Casting technieken',
        'In de laatste workshop die we aanbieden leren we de LMTS-artiesten hoe ze zich het best kunnen voorbereiden op een casting call. We leren ze monologen voorbrengen, hoe ze teksten het best interpreteren… Zo kunnen zij net als anderen met een evenwaardige kans de castingruimtes binnenstappen',
        'Bij deze workshop krijg je verschillende tips en tricks om je voor te bereiden voor een goed casting gesprek.', 'Mechelen', 'ct',true);

INSERT INTO TEACHER (ID, NAME, BIO, EXPERIENCE,image)
VALUES (nextval('TEACHER_SEQ'), 'KAREN BOONS',
        'Hallo ik ben Karen, ik ben 32 jaar en werk al 5 jaar bij "Creative Spirits". Ik ben de choreograaf die niets liever doet dan mijn passie voor dansen over te brengen aan beginners.',
        '10 jaar modern ballet, 6 jaar hiphop' ,'https://d23rta9s95jzo8.cloudfront.net/static_pictures/karen.jpg');
INSERT INTO TEACHER (ID, NAME, BIO, EXPERIENCE,image)
VALUES (nextval('TEACHER_SEQ'), 'JOEP DE KLEINE',
        'Hallo ik ben Joep, ik ben 27 jaar en werk reeds 3 jaar bij "Creative Spirits". Ik ben de zanginstructeur en help soms ook mee als assistent bij de danscursussen die wij ook aanbieden. Zingen voor een publiek is niet voor iedereen weggelegt maar ik doe er alles aan om de beste zanger in je boven te halen',
        'Master aan de Dutch National Opera Acedemy,2 jaar hiphop en 6 jaar in een band ','https://d23rta9s95jzo8.cloudfront.net/static_pictures/joep.jpg');
INSERT INTO TEACHER (ID, NAME, BIO, EXPERIENCE,image)
VALUES (nextval('TEACHER_SEQ'), 'KAREL BERG',
        'Hallo ik ben Karel, ik ben 41 jaar en werk al 12 jaar bij "Screen Masters". Acteren zat al van jongs af aan in mijn interessepakket en daarom speelde ik bij elk schooltoneel mee. Later ben ik dan ook verder gaan studeren in die richting',
        'Ik heb de academische bachelor- en masteropleiding in het Drama met afstudeerrichting Acteren ','https://d23rta9s95jzo8.cloudfront.net/static_pictures/karel.jpg');
INSERT INTO COMPANY(ID, NAME, BIO, LOCATION)
VALUES (nextval('COMPANY_SEQ'), 'Creative Spirits',
        'Wij zijn een VZW dat ons vooral bezig houd met cursussen geven aan mensen met een beperking. \nWij geven dans , zang en muziek lessen voor verschillende niveaus.',
        'Mechelen');
    INSERT
INTO COMPANY(ID, NAME, BIO, LOCATION)
VALUES (nextval('COMPANY_SEQ'), 'Screen Masters', 'Bij Screen Masters stomen wij jullie helemaal klaar om voor het scherm of op het podium te schitteren! \nMet behulp van professionals hopen wij mensen met een beperking ook de kans te geven om te stralen voor een publiek.', 'Antwerpen');

insert into TEACHER_COURSES (TEACHER_ID, COURSES_ID)
values (1, 1);
insert into COMPANY_COURSES (COMPANY_ID, COURSES_ID)
values (0, 1);
insert into TEACHER_COURSES (TEACHER_ID, COURSES_ID)
values (0, 0);

insert into TEACHER_COURSES (TEACHER_ID, COURSES_ID)
values (1, 0);
insert into COMPANY_COURSES (COMPANY_ID, COURSES_ID)
values (0, 0);
insert into TEACHER_COURSES (TEACHER_ID, COURSES_ID)
values (2, 2);
insert into COMPANY_COURSES (COMPANY_ID, COURSES_ID)
values (1, 2);

